### ISSUE TITLE
Local time is not good

### ISSUE THREAD

**Issue by bubnovKelnik** [bubnovKelnik/mediaopt-test-task#1]
As it is written in task text:

> the workstation transmits the employee number and the current time to the web service

It is no good to trust user's time. I will use system time. If users are working all over the world - it is better get time shift from user or, better - define it in db.

Your ideas?

**Comment by am-** [comment]
You're right. For the sake of the exercise, we assume that (1) each workstation synchronizes via NTP, (2) the user cannot change the system time and (3) the transmitted time is assumed to be UTC.

**Comment by bubnovKelnik** [comment]
No need to transfer identical data (datetime) from client to server.
I already use server time in login/logout actions - never trust user`s input :)

**Comment by bubnovKelnik** [comment]
This will do everything much more easy.
User know his id, optional - the project`s id.
He realy don`t need to care about time.

**Comment by am-** [comment]
This is absolutely fine. :-)
