### ISSUE TITLE
Misunderstood of Peak Time

### ISSUE THREAD

**Issue by bubnovKelnik** [bubnovKelnik/mediaopt-test-task#2]
Task: Given a day and project, implement an operation that determines a time period (on the given day) in which most people were working on the given project.

Ok, let it be the project A and 2 users Mike and Lucy.
Mike worked on project A from 12:30 till 14:30 and from 17:00 till 18:30
Lucy worked on project A from 12:00 till 14:00 and from 17:00 till 18:30

We got N hours of common work of 2 employees (Mike and Lucy):
- 1.5 hours in interval 12:30-14:00
- 1.5 hours in interval 17:00-18:30

What time period the service should return? Both? Or if the second interval whould be less then first?

**Comment by am-** [comment]
I'm glad you noticed that there is no single peak time. According to the task, it suffices to return one interval. That is, choose one interval as you like.

**Comment by bubnovKelnik** [comment]
If intervals are not equal - I should return the longest one, right?

**Comment by bubnovKelnik** [comment]
Hm...
I think that the task does not reflect the real needs of the management.
If we have 1 interval (15 seconds) with 3 workers and 1 interval (5 hours) with 2 workers - which one is the a real peak interval?

**Comment by am-** [comment]
Great questions. :-)

With regard to the first question: It is sensible (but not mandatory) to return one of the longest peak intervals.

Your second question concerns the optimization condition, which can be made arbitrarily complex. For our sample problem, we just need a single interval, in which most employees were working simultaneously. In your example, this would be the 15s interval. That being said: I'm totally fine if your optimization condition is the product of the interval and the number of employees.

**Comment by bubnovKelnik** [comment]
Ok.
I will assume that employee can not work on the same project in more then one session at the same time.
I will look for time intervals ordered by count of employees were working simultaneously and if they are equal, ordered by interval length.

**Comment by bubnovKelnik** [comment]
Have to contribute to https://github.com/beberlei/DoctrineExtensions for CASE WHEN support in Sqlite

**Comment by bubnovKelnik** [comment]
Done
